version: '3.8'

services:
  backend:
    build: ../apps/backend
    environment:
      PORT: 3000
      WS_PORT: 3001
      JWT_SECRET: dev_secret
      REDIS_URL: redis://redis:6379
      OSRM_URL: http://osrm:5000
      DATABASE_URL: postgres://user:pass@postgres:5432/ride
    ports:
      - '3000:3000'
      - '3001:3001'
    depends_on:
      - redis
      - osrm
      - postgres
    networks:
      - ride-network

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    networks:
      - ride-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  osrm:
    image: osrm/osrm-backend:latest
    command: osrm-routed --algorithm mld /data/rwanda-latest.osrm
    ports:
      - '5050:5000' # Using 5050 externally (5000 often used by AirPlay on macOS)
    volumes:
      - ./osrm:/data
    networks:
      - ride-network

  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: ride
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ride-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d ride']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ride-network:
    driver: bridge

volumes:
  postgres_data:
